### ISSUE TITLE
Cluster label out of place

### ISSUE THREAD

**Issue by hezronobuchele** [cavis/leafpile#1]
Hi,

Great tool you're developing. Just starting out on Leaflet + D3 and stumbled across this while looking for clustering solutions for Leaflet. The labels however are way off on my browser. Is it the version of leaflet I'm using (latest from the repo) or a CSS issue? The labels appear at the top left edge of the circle images instead of the center.

Cheers!
Hezron

**Comment by cavis** [comment]
Hey Hezron, can you include a screenshot, and tell me what browser/version/os you're on?  Thanks.

**Comment by hezronobuchele** [comment]
http://www.flickr.com/photos/83625493@N08/7652083974/in/photostream I'm seeing this on Firefox 14, hope you can see the count 5 on the top left corner of the cluster
